const fs = require('node:fs');
const path = require('node:path');
const files = ['config','copy','clue-copy','rng','map','clues','solver','generator','game','audio','ui','tests','main'];
const body = files.map(name => `// ---- ${name}.js ----\n` + fs.readFileSync(path.join(__dirname, 'js', name+'.js'), 'utf8').replace(/^import .*;\r?\n/gm, '').replace(/\bexport\s+/g, '')).join('\n');
fs.writeFileSync(path.join(__dirname, 'js/app.bundle.js'), `/* Generated by node build.cjs */\n(() => {\n'use strict';\n${body}\n})();\n`);
