const fs = require('node:fs');
const path = require('node:path');
const strip = (name) => fs.readFileSync(path.join(__dirname, 'js', name + '.js'), 'utf8').replace(/^import .*;\r?\n/gm, '').replace(/\bexport\s+/g, '');
const files = ['config','copy','clue-copy','rng','map','clues','solver','generator','daily-v1','daily','online','football','boat','game','audio','car','board-controls','ui','tests','main'];
const body = files.map(name => `// ---- ${name}.js ----\n` + strip(name)).join('\n');
fs.writeFileSync(path.join(__dirname, 'js/app.bundle.js'), `/* Generated by node build.cjs */\n(() => {\n'use strict';\n${body}\n})();\n`);

// Núcleo lógico para la función del servidor que valida el misterio diario: el
// mismo generador, el mismo solver y la misma reproducción de acciones que el
// navegador, sin DOM. Se regenera con cada build para que nunca diverjan.
const core = ['config','copy','clue-copy','rng','map','clues','solver','generator','daily-v1','daily'];
const coreBody = core.map(name => `// ---- ${name}.js ----\n` + strip(name)).join('\n');
const coreExports = 'export { CONFIG, DAILY_VERSIONS, DAILY_EPOCH, dailyDateKey, dailyVersionFor, dailySeed, generateDailyLevel, dailyFingerprint, replayDaily, gradeDaily, shiftDateKey, isDateKey, msUntilNextDaily };';
const coreDir = path.join(__dirname, 'supabase', 'functions', '_shared');
fs.mkdirSync(coreDir, { recursive: true });
fs.writeFileSync(path.join(coreDir, 'vecindario-core.mjs'), `/* Generated by node build.cjs — no editar a mano */\n${coreBody}\n${coreExports}\n`);
